# Generated by Django 4.1.4 on 2023-01-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitUserName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('adjective', 'Adjective'), ('subject', 'Subject')], max_length=15)),
                ('value', models.CharField(max_length=8)),
            ],
        ),
    ]
