# Generated by Django 4.1.4 on 2023-02-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_authentication',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='initusername',
            name='kind',
            field=models.CharField(choices=[('header', 'Header'), ('footer', 'Footer')], max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(editable=False, max_length=30),
        ),
    ]
