# Generated by Django 4.1.4 on 2023-02-19 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alarm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InitUserName',
            new_name='RandomName',
        ),
    ]
