# Generated by Django 4.1.4 on 2023-02-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_email_authentication_alter_initusername_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_authentication',
            field=models.BooleanField(default=False, help_text='authentication by email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
