# Generated by Django 4.1.4 on 2023-02-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notification_delete_alarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='message',
            field=models.CharField(default='', max_length=120, null=True),
        ),
    ]
