# Generated by Django 4.1.4 on 2023-02-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blog',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.URLField(null=True),
        ),
    ]
