# Generated by Django 4.1.4 on 2023-02-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_career'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='message',
            new_name='introduce',
        ),
    ]
