# Generated by Django 4.1.4 on 2023-01-28 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_alter_answer_question'),
        ('questions', '0003_alter_question_creator_alter_question_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='select_answer',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='select_question', to='answers.answer'),
        ),
    ]
