databases:
  - name: qding
    databaseName: qding
    user: qding
    region: singapore

services:
  - type: web
    name: qding
    env: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn qding.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: qding
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4