# Generated by Django 4.1.4 on 2023-02-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.URLField()),
                ('category', models.CharField(choices=[('qna_question', 'Qna_Question'), ('qna_answer', 'Qna_Answer'), ('profile_image', 'Profile_Image')], default='qna_answer', max_length=15, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
