# Generated by Django 4.1.4 on 2023-02-08 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
