# Generated by Django 4.1.4 on 2023-02-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('qna_question', 'Qna_Question'), ('qna_answer', 'Qna_Answer'), ('profile_image', 'Profile_Image')], max_length=15),
        ),
    ]
