# Generated by Django 4.1.4 on 2023-02-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnas', '0002_question_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='조회수 / 쿠키 기반 중복 방지'),
        ),
    ]
