# Generated by Django 4.1.4 on 2023-02-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnas', '0003_alter_question_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(),
        ),
    ]
