# Generated by Django 4.1.4 on 2023-02-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnas', '0004_alter_question_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='view_count',
        ),
        migrations.AlterField(
            model_name='answer',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='조회수 / 쿠키 기반 중복 방지'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='question',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='조회수 / 쿠키 기반 중복 방지'),
        ),
    ]
