# Generated by Django 4.1.4 on 2023-02-19 02:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qnas', '0005_questionvote_target_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='notification_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
