# Generated by Django 4.1.4 on 2023-02-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnas', '0005_tag_remove_question_view_count_alter_answer_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(to='qnas.tag'),
        ),
    ]
