# Generated by Django 4.1.4 on 2023-02-22 00:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qnas', '0007_answervote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='notification_user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
