# Generated by Django 4.1.4 on 2023-02-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnas', '0009_alter_question_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(related_name='questions', to='qnas.tag'),
        ),
    ]
