# Generated by Django 4.1.4 on 2023-02-24 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnas', '0010_alter_question_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answervote',
            old_name='votes',
            new_name='vote_type',
        ),
        migrations.RenameField(
            model_name='questionvote',
            old_name='votes',
            new_name='vote_type',
        ),
    ]
